# Generated by Django 3.0.7 on 2021-11-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
            ],
        ),
    ]
