# Generated by Django 3.0.7 on 2021-11-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20211117_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='photo',
        ),
    ]
