# Generated by Django 3.0.7 on 2021-11-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_remove_mascota_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='photo',
            field=models.ImageField(default=3, upload_to='images'),
            preserve_default=False,
        ),
    ]
